version: '3.5'

services:
  sender:
    build: sender
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: test
      RABBITMQ_PASS: test
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: icaruus
      RABBITMQ_DEFAULT_PASS: icaruus
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  receiver:
    build: receiver
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: test
      RABBITMQ_PASS: test
    restart: 'on-failure'
    depends_on:
      - rabbitmq
