version: '3.5'

services:
  # sender:
  #   build: sender
  #   environment:
  #     RABBITMQ_HOST: rabbitmq-app
  #     RABBITMQ_PORT: 5672
  #     RABBITMQ_USER: test
  #     RABBITMQ_PASS: test

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test

  receiver:
    build: receiver
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    depends_on:
      - rabbitmq
