version: '3.5'

services:
  rabbitmq-app:
    image: rabbitmq:3.9.13-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
      # COMPUTERNAME: localhost
    # volumes:
    #   - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
